//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wf_app.resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resource_panel_select_criteria {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resource_panel_select_criteria() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wf_app.resources.resource_panel_select_criteria", typeof(resource_panel_select_criteria).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -.
        /// </summary>
        internal static string _btn_clear_text {
            get {
                return ResourceManager.GetString("_btn_clear_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить фильтр.
        /// </summary>
        internal static string _btn_clear_tip {
            get {
                return ResourceManager.GetString("_btn_clear_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать фильтр по пользователям ВБР.
        /// </summary>
        internal static string _btn_declarant_tip {
            get {
                return ResourceManager.GetString("_btn_declarant_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать фильтр по ВБР.
        /// </summary>
        internal static string _btn_fish_tip {
            get {
                return ResourceManager.GetString("_btn_fish_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать фильтр по видам квоты.
        /// </summary>
        internal static string _btn_regime_tip {
            get {
                return ResourceManager.GetString("_btn_regime_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать фильтр по районам промысла.
        /// </summary>
        internal static string _btn_region_tip {
            get {
                return ResourceManager.GetString("_btn_region_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на +.
        /// </summary>
        internal static string _btn_select_text {
            get {
                return ResourceManager.GetString("_btn_select_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать фильтр по субъектам РФ.
        /// </summary>
        internal static string _btn_subject_tip {
            get {
                return ResourceManager.GetString("_btn_subject_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистика:.
        /// </summary>
        internal static string _cbx_stat {
            get {
                return ResourceManager.GetString("_cbx_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Год:.
        /// </summary>
        internal static string _cbx_year {
            get {
                return ResourceManager.GetString("_cbx_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Процент:.
        /// </summary>
        internal static string _num_percent {
            get {
                return ResourceManager.GetString("_num_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь ВБР:.
        /// </summary>
        internal static string _x_declarant {
            get {
                return ResourceManager.GetString("_x_declarant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВБР:.
        /// </summary>
        internal static string _x_fish {
            get {
                return ResourceManager.GetString("_x_fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вид квоты:.
        /// </summary>
        internal static string _x_regime {
            get {
                return ResourceManager.GetString("_x_regime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Район промысла:.
        /// </summary>
        internal static string _x_region {
            get {
                return ResourceManager.GetString("_x_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Субъект РФ:.
        /// </summary>
        internal static string _x_subject {
            get {
                return ResourceManager.GetString("_x_subject", resourceCulture);
            }
        }
    }
}
