--РЕЕСТР ДОЛЕЙ, ЗАКРЕПЛЁННЫХ ЗА ПОЛЬЗОВАТЕЛЯМИ ВБР
CREATE TABLE [dbo].[portion]
(
	[id_history] INT NOT NULL PRIMARY KEY,
	[id_declarant] INT NOT NULL,
	[id_basin] INT NOT NULL,
	[id_regime] INT NOT NULL,
	[id_region] INT NOT NULL,
	[id_fish] INT NOT NULL,
	[id_subject] INT NOT NULL,
    [portion] DECIMAL(38,17) NULL, 
	[date_open] DATETIME NULL,
	[date_close] DATETIME NULL,
    [report_organization] NVARCHAR(150) NULL, 
    [report_number] NVARCHAR(60) NULL, 
    [report_date] DATETIME NULL, 
    [report_document] NVARCHAR(150) NULL, 
    [contract_organization] NVARCHAR(150) NULL, 
    [contract_number] NVARCHAR(60) NULL, 
    [contract_date] DATETIME NULL, 
    [contract_cancel_organization] NVARCHAR(150) NULL, 
    [contract_cancel_number] NVARCHAR(150) NULL, 
    [contract_cancel_date] DATETIME NULL, 
    [contract_cancel_document] NVARCHAR(50) NULL, 
    [transfer_number] NVARCHAR(150) NULL, 
    [transfer_date] DATETIME NULL, 
    [transfer_reason] NVARCHAR(150) NULL, 
    [note] NVARCHAR(64) NULL, 
    [responsible] NVARCHAR(64) NULL, 
    [timestamp_] DATETIME NULL,
	[id_declarant_history] INT NULL
)
