//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfmc.quotas.resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class rc_report_catch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rc_report_catch() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("report_WBR_catch.gui.form_report_WBR_catch.rc_report_catch", typeof(rc_report_catch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        internal static string btn_exit {
            get {
                return ResourceManager.GetString("btn_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт.
        /// </summary>
        internal static string btn_export {
            get {
                return ResourceManager.GetString("btn_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порядок.
        /// </summary>
        internal static string btn_order {
            get {
                return ResourceManager.GetString("btn_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выборка.
        /// </summary>
        internal static string btn_select {
            get {
                return ResourceManager.GetString("btn_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на данные оперативки.
        /// </summary>
        internal static string cbx_stat_item_o {
            get {
                return ResourceManager.GetString("cbx_stat_item_o", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на o.
        /// </summary>
        internal static string cbx_stat_item_o_data {
            get {
                return ResourceManager.GetString("cbx_stat_item_o_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на данные статистики.
        /// </summary>
        internal static string cbx_stat_item_s {
            get {
                return ResourceManager.GetString("cbx_stat_item_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на s.
        /// </summary>
        internal static string cbx_stat_item_s_data {
            get {
                return ResourceManager.GetString("cbx_stat_item_s_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на данные статистики, оперативки.
        /// </summary>
        internal static string cbx_stat_item_so {
            get {
                return ResourceManager.GetString("cbx_stat_item_so", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на so.
        /// </summary>
        internal static string cbx_stat_item_so_data {
            get {
                return ResourceManager.GetString("cbx_stat_item_so_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вылов.
        /// </summary>
        internal static string column_catch {
            get {
                return ResourceManager.GetString("column_catch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь ВБР.
        /// </summary>
        internal static string column_declarant {
            get {
                return ResourceManager.GetString("column_declarant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВБР.
        /// </summary>
        internal static string column_fish {
            get {
                return ResourceManager.GetString("column_fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИНН.
        /// </summary>
        internal static string column_inn {
            get {
                return ResourceManager.GetString("column_inn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Квота.
        /// </summary>
        internal static string column_limit {
            get {
                return ResourceManager.GetString("column_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на %.
        /// </summary>
        internal static string column_percent {
            get {
                return ResourceManager.GetString("column_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доля, %.
        /// </summary>
        internal static string column_portion {
            get {
                return ResourceManager.GetString("column_portion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Район промысла.
        /// </summary>
        internal static string column_region {
            get {
                return ResourceManager.GetString("column_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регион РФ.
        /// </summary>
        internal static string column_subject {
            get {
                return ResourceManager.GetString("column_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выборка данных освоения квот.
        /// </summary>
        internal static string form_title {
            get {
                return ResourceManager.GetString("form_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь ВБР:.
        /// </summary>
        internal static string lbl_declarant {
            get {
                return ResourceManager.GetString("lbl_declarant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Процент:.
        /// </summary>
        internal static string lbl_percent {
            get {
                return ResourceManager.GetString("lbl_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вид промысла:.
        /// </summary>
        internal static string lbl_regime {
            get {
                return ResourceManager.GetString("lbl_regime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Район промысла:.
        /// </summary>
        internal static string lbl_region {
            get {
                return ResourceManager.GetString("lbl_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные:.
        /// </summary>
        internal static string lbl_stat_data {
            get {
                return ResourceManager.GetString("lbl_stat_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Субъект РФ:.
        /// </summary>
        internal static string lbl_subject {
            get {
                return ResourceManager.GetString("lbl_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВБР:.
        /// </summary>
        internal static string lbl_WBR {
            get {
                return ResourceManager.GetString("lbl_WBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Год:.
        /// </summary>
        internal static string lbl_year {
            get {
                return ResourceManager.GetString("lbl_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        internal static string msgbox_exception_title {
            get {
                return ResourceManager.GetString("msgbox_exception_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип исключительной ситуации:.
        /// </summary>
        internal static string msgbox_exception_type {
            get {
                return ResourceManager.GetString("msgbox_exception_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка экспорта данных.
        /// </summary>
        internal static string msgbox_export_message {
            get {
                return ResourceManager.GetString("msgbox_export_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка выборки данных.
        /// </summary>
        internal static string msgbox_select_message {
            get {
                return ResourceManager.GetString("msgbox_select_message", resourceCulture);
            }
        }
    }
}
